# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to access-workgroup module."
  name: ":floppy_disk: athena-workgroup"
- color: "fbca04"
  description: "This issue or pull request is related to quicksight-folder module."
  name: ":floppy_disk: quicksight-folder"
- color: "fbca04"
  description: "This issue or pull request is related to quicksight-group module."
  name: ":floppy_disk: quicksight-group"
- color: "fbca04"
  description: "This issue or pull request is related to quicksight-namespace module."
  name: ":floppy_disk: quicksight-namespace"
- color: "fbca04"
  description: "This issue or pull request is related to s3-access-point module."
  name: ":floppy_disk: s3-access-point"
- color: "fbca04"
  description: "This issue or pull request is related to s3-bucket module."
  name: ":floppy_disk: s3-bucket"
