# Modules
":floppy_disk: athena-data-catalog":
- changed-files:
  - any-glob-to-any-file:
    - modules/athena-data-catalog/**/*

":floppy_disk: athena-workgroup":
- changed-files:
  - any-glob-to-any-file:
    - modules/athena-workgroup/**/*

":floppy_disk: glue-connection":
- changed-files:
  - any-glob-to-any-file:
    - modules/glue-connection/**/*

":floppy_disk: glue-crawler":
- changed-files:
  - any-glob-to-any-file:
    - modules/glue-crawler/**/*

":floppy_disk: glue-data-catalog":
- changed-files:
  - any-glob-to-any-file:
    - modules/glue-data-catalog/**/*

":floppy_disk: glue-database":
- changed-files:
  - any-glob-to-any-file:
    - modules/glue-database/**/*

":floppy_disk: glue-table":
- changed-files:
  - any-glob-to-any-file:
    - modules/glue-table/**/*

":floppy_disk: quicksight-folder":
- changed-files:
  - any-glob-to-any-file:
    - modules/quicksight-folder/**/*

":floppy_disk: quicksight-group":
- changed-files:
  - any-glob-to-any-file:
    - modules/quicksight-group/**/*

":floppy_disk: quicksight-namespace":
- changed-files:
  - any-glob-to-any-file:
    - modules/quicksight-namespace/**/*

":floppy_disk: s3-access-point":
- changed-files:
  - any-glob-to-any-file:
    - modules/s3-access-point/**/*

":floppy_disk: s3-bucket":
- changed-files:
  - any-glob-to-any-file:
    - modules/s3-bucket/**/*
