# Modules
":floppy_disk: athena-data-catalog":
- modules/athena-data-catalog/**/*
":floppy_disk: athena-workgroup":
- modules/athena-workgroup/**/*
":floppy_disk: quicksight-folder":
- modules/quicksight-folder/**/*
":floppy_disk: quicksight-group":
- modules/quicksight-group/**/*
":floppy_disk: quicksight-namespace":
- modules/quicksight-namespace/**/*
":floppy_disk: s3-access-point":
- modules/s3-access-point/**/*
":floppy_disk: s3-bucket":
- modules/s3-bucket/**/*
