# Modules
- color: "fbca04"
  description: "This issue or pull request is related to athena-data-catalog module."
  name: ":floppy_disk: athena-data-catalog"
- color: "fbca04"
  description: "This issue or pull request is related to athena-workgroup module."
  name: ":floppy_disk: athena-workgroup"
- color: "fbca04"
  description: "This issue or pull request is related to glue-connection module."
  name: ":floppy_disk: glue-connection"
- color: "fbca04"
  description: "This issue or pull request is related to glue-crawler module."
  name: ":floppy_disk: glue-crawler"
- color: "fbca04"
  description: "This issue or pull request is related to glue-data-catalog module."
  name: ":floppy_disk: glue-data-catalog"
- color: "fbca04"
  description: "This issue or pull request is related to glue-database module."
  name: ":floppy_disk: glue-database"
- color: "fbca04"
  description: "This issue or pull request is related to glue-table module."
  name: ":floppy_disk: glue-table"
- color: "fbca04"
  description: "This issue or pull request is related to lakeformation-data-catalog module."
  name: ":floppy_disk: lakeformation-data-catalog"
- color: "fbca04"
  description: "This issue or pull request is related to s3-access-point module."
  name: ":floppy_disk: s3-access-point"
- color: "fbca04"
  description: "This issue or pull request is related to s3-bucket module."
  name: ":floppy_disk: s3-bucket"
